-- MySQL Script generated by MySQL Workbench
-- Fri Sep 11 08:38:02 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stock_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stock_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock_management` DEFAULT CHARACTER SET utf8 ;
USE `stock_management` ;

-- -----------------------------------------------------
-- Table `stock_management`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`country` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`country` (
  `country_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `currency` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `updated_at` DATETIME NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`country_id`)  COMMENT '',
  UNIQUE INDEX `name` (`name` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stock_management`.`clinic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`clinic` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`clinic` (
  `clinic_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `street` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `city` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `province` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `post_code` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `telephone_number` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `fax_number` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `clinic_number` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `latitude` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `longitude` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `country_id` INT(11) NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `updated_at` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`clinic_id`)  COMMENT '',
  INDEX `fk_clinic_country_idx` (`country_id` ASC)  COMMENT '',
  CONSTRAINT `fk_clinic_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `stock_management`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stock_management`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`employee` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`employee` (
  `employee_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `last_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `full_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `role` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `active` CHAR(1) NULL DEFAULT NULL COMMENT '',
  `start_date` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `telephone_number` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `address` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `clinic_id` INT(11) NOT NULL COMMENT '',
  `employee_code` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`employee_id`)  COMMENT '',
  INDEX `fk_employee_clinic1_idx` (`clinic_id` ASC)  COMMENT '',
  CONSTRAINT `fk_employee_clinic1`
    FOREIGN KEY (`clinic_id`)
    REFERENCES `stock_management`.`clinic` (`clinic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stock_management`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`patient` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`patient` (
  `patient_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `email` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `first_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `last_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `full_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `occupation` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `company_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `phone` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `date_of_birth` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `address` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`patient_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stock_management`.`tax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`tax` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`tax` (
  `tax_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `percent` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `country_id` INT(11) NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `updated_at` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`tax_id`)  COMMENT '',
  INDEX `fk_tax_country1_idx` (`country_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tax_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `stock_management`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stock_management`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`invoice` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`invoice` (
  `invoice_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `date` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `total` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `tax` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `employee_id` INT(11) NOT NULL COMMENT '',
  `status` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `patient_id` INT(11) NOT NULL COMMENT '',
  `tax_id` INT(11) NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `updated_at` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`invoice_id`)  COMMENT '',
  INDEX `fk_invoice_employee1_idx` (`employee_id` ASC)  COMMENT '',
  INDEX `fk_invoice_patient1_idx` (`patient_id` ASC)  COMMENT '',
  INDEX `fk_invoice_tax1_idx` (`tax_id` ASC)  COMMENT '',
  CONSTRAINT `fk_invoice_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `stock_management`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `stock_management`.`patient` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_tax1`
    FOREIGN KEY (`tax_id`)
    REFERENCES `stock_management`.`tax` (`tax_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = 'employee_employee_id';


-- -----------------------------------------------------
-- Table `stock_management`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`product` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`product` (
  `product_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `type` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `price` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `quantity_on_hand` INT(11) NULL DEFAULT NULL COMMENT '',
  `clinic_id` INT(11) NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `updated_at` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`product_id`)  COMMENT '',
  INDEX `fk_product_clinic1_idx` (`clinic_id` ASC)  COMMENT '',
  CONSTRAINT `fk_product_clinic1`
    FOREIGN KEY (`clinic_id`)
    REFERENCES `stock_management`.`clinic` (`clinic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stock_management`.`back_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`back_order` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`back_order` (
  `back_order_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `date` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `invoice_id` INT(11) NOT NULL COMMENT '',
  `product_id` INT(11) NOT NULL COMMENT '',
  `quantity` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`back_order_id`)  COMMENT '',
  INDEX `fk_back_order_invoice1_idx` (`invoice_id` ASC)  COMMENT '',
  INDEX `fk_back_order_product1_idx` (`product_id` ASC)  COMMENT '',
  CONSTRAINT `fk_back_order_invoice1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `stock_management`.`invoice` (`invoice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_back_order_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `stock_management`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stock_management`.`vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`vendor` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`vendor` (
  `vendor_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `address` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `phone` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `contact` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `fax` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `notes` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `updated_at` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`vendor_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stock_management`.`component`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`component` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`component` (
  `component_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `cost` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `quantityOnHand` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `description` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `vendor_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`component_id`)  COMMENT '',
  INDEX `fk_component_vendor1_idx` (`vendor_id` ASC)  COMMENT '',
  CONSTRAINT `fk_component_vendor1`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `stock_management`.`vendor` (`vendor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stock_management`.`invoice_product_quantity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`invoice_product_quantity` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`invoice_product_quantity` (
  `quantity` INT(11) NOT NULL COMMENT '',
  `invoice_invoice_id` INT(11) NOT NULL COMMENT '',
  `product_product_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`invoice_invoice_id`, `product_product_id`)  COMMENT '',
  INDEX `fk_invoice_product_quantity_invoice1_idx` (`invoice_invoice_id` ASC)  COMMENT '',
  INDEX `fk_invoice_product_quantity_product1_idx` (`product_product_id` ASC)  COMMENT '',
  CONSTRAINT `fk_invoice_product_quantity_invoice1`
    FOREIGN KEY (`invoice_invoice_id`)
    REFERENCES `stock_management`.`invoice` (`invoice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_product_quantity_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `stock_management`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stock_management`.`product_component`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`product_component` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`product_component` (
  `component_id` INT(11) NOT NULL COMMENT '',
  `product_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`component_id`, `product_id`)  COMMENT '',
  INDEX `fk_product_component_component1_idx` (`component_id` ASC)  COMMENT '',
  INDEX `fk_product_component_product1_idx` (`product_id` ASC)  COMMENT '',
  CONSTRAINT `fk_product_component_component1`
    FOREIGN KEY (`component_id`)
    REFERENCES `stock_management`.`component` (`component_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_component_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `stock_management`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stock_management`.`stock_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`stock_order` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`stock_order` (
  `stock_order_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `is_paid` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `total` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `tax` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `vendor_id` INT(11) NOT NULL COMMENT '',
  `tax_id` INT(11) NOT NULL COMMENT '',
  `items_received` CHAR(1) NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `updated_at` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`stock_order_id`)  COMMENT '',
  INDEX `fk_stock_order_vendor1_idx` (`vendor_id` ASC)  COMMENT '',
  INDEX `fk_stock_order_tax1_idx` (`tax_id` ASC)  COMMENT '',
  CONSTRAINT `fk_stock_order_tax1`
    FOREIGN KEY (`tax_id`)
    REFERENCES `stock_management`.`tax` (`tax_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_order_vendor1`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `stock_management`.`vendor` (`vendor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stock_management`.`stock_order_line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_management`.`stock_order_line` ;

CREATE TABLE IF NOT EXISTS `stock_management`.`stock_order_line` (
  `stock_order_id` INT(11) NOT NULL COMMENT '',
  `product_id` INT(11) NOT NULL COMMENT '',
  `quantity` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `updated_at` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`stock_order_id`, `product_id`)  COMMENT '',
  INDEX `fk_stock_order_line_stock_order1_idx` (`stock_order_id` ASC)  COMMENT '',
  INDEX `fk_stock_order_line_product1_idx` (`product_id` ASC)  COMMENT '',
  CONSTRAINT `fk_stock_order_line_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `stock_management`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_order_line_stock_order1`
    FOREIGN KEY (`stock_order_id`)
    REFERENCES `stock_management`.`stock_order` (`stock_order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
